  - name: "pymysql install"
    ansible.builtin.apt:
      name: "python3-pymysql"
      state: "latest"
      update_cache: true

  - name: "mysql install"
    ansible.builtin.apt:
      name: "mysql-server"
      state: "latest"
      update_cache: true

  - name: "root user"
    community.mysql.mysql_user:
      name: "root"
      password: "password"
      login_user: "root"
      login_password: "password"
      check_implicit_admin: true
      login_unix_socket: "/var/run/mysqld/mysqld.sock"

  - name: "delete anons"
    community.mysql.mysql_user:
      name: ""
      state: "absent"
      login_user: "root"
      login_password: "password"

  - name: "delete test db"
    community.mysql.mysql_db:
      name: "test"
      state: "absent"
      login_user: "root"
      login_password: "password"