- name: Create swarm cluster
  community.docker.docker_swarm:
    advertise_addr: "{{ ansible_host }}"
    state: present
  register: token
  when: "'leader' in group_names"

- name: Get join-token for nodes
  ansible.builtin.set_fact:
    join_token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    join_token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"

- name: Create a directory for join tokens
  ansible.builtin.file:
    path: ./tokens
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Save manager token to file
  ansible.builtin.copy:
    dest: ./tokens/token_manager
    content: "{{ join_token_manager }}"
    mode: '0600'
  delegate_to: localhost

- name: Save worker token to file
  ansible.builtin.copy:
    dest: ./tokens/token_worker
    content: "{{ join_token_worker }}"
    mode: '0600'
  delegate_to: localhost
