  - name: "nginx install"
    ansible.builtin.apt:
      name: "nginx"
      state: "latest"
      update_cache: true

  - name: "delete /var/www/html"
    ansible.builtin.file:
      path: "/var/www/html"
      state: "absent"

  - name: "copy site content"
    ansible.builtin.copy:
      src: "files/html"
      dest: "/var/www/"
      owner: "vagrant"
      group: "vagrant"
      mode: "0644"